### ISSUE TITLE
  触摸板容易误触，可以关闭吗？

### ISSUE THREAD

**Issue by lukekong** [jardenliu/XPS15-9560-Mojave#10]
在辅助功能里面有选项，但是无法关闭。希望可以关闭触摸板，打字方便，改用蓝牙鼠标。谢谢！

**Comment by jardenliu** [comment]
不开起轻触还会误触吗？

**Comment by lukekong** [comment]
我按照您的指点，关闭“触控板的轻点来点按”，这样打字就不会误触，打字的光标也不会飞走了。谢谢！

**Comment by liqiantu** [comment]
我的辅助功能里忽略触控板可以关闭
用的是最新VoodooI2C
