### ISSUE TITLE
大神能做个风扇策略吗？

### ISSUE THREAD

**Issue by zzzqqqhhh** [jardenliu/XPS15-9560-Mojave#11]
首先感谢大神能提供配置文件造福9560机友，目前已经有很多机友装上mojave后一切工作正常。
在这里再提一个意见啊，能否在黑苹果平台上实现温度控制？类似macfanscontrol/windows平台上的Dell Command Power Manager，设置静音模式，风扇在低负载下能尽可能不转。
xps15黑果交流群：275702487

**Comment by jardenliu** [comment]
并不会这个高深的东西
