### ISSUE TITLE
USB引起的睡眠问题及解决，希望能些用

### ISSUE THREAD

**Issue by foxni** [jardenliu/XPS15-9560-Mojave#12]
使用USBPower替换USBInjectAll之后USB的识别使用并没有发现问题，但是却有一些莫名其妙的小问题，不知道各位是否碰到。
1.睡眠无故被唤醒，非合盖状态下闲置一段时间后会自动睡眠，但是睡不了多久就会被自动唤醒，检查唤醒原因，后面是一长串的硬件名称，Google一下发现有人之前也碰到过，说是重置下BIOS就恢复了，尝试了一下，甚至升级到最新的BIOS也没能解决（当然是已经关闭了睡眠小憩功能的前提下出现的）。
2.睡眠唤醒后网络变慢ping值延迟很高（替换的DW1830），这个问题之前10.13也有，通过关闭『唤醒以供wifi网络访问』选项可以解决，但是这次却不行了。
通过多方查找分析，最后发现WIFI网卡被识别为第三方网卡，而我记得之前在10.13的时候是可以识别为『AirPort Extreme』，于是把USBPower重新替换回USBInjectAll之后，wifi网卡被重新识别『AirPort Extreme』。
至此，以上问题全部解决，目前使用已经一周多，没有发现任何后遗症。
除此之外，我去除了BT4LEContiunityFixup.kext ，仍然使用的『Enable BT4LE-Handoff-Hotspot』patch，whatevergreen 使用的agdpmod=vit9696参数patch AGDP，目前蓝牙表现良好（本次10.14更新确实极大提升了hand off之类依赖蓝牙的功能，对蓝牙提升很大，是我这次升级的最大动力），hdmi外接输出良好（非4k输出）。
最后，再次感谢楼主提供的10.14解决方案。

**Comment by jardenliu** [comment]
你说的问题我都没遇到。。。。。

**Comment by jardenliu** [comment]
1.9.1

**Comment by foxni** [comment]
@jardenliu 好吧，也许跟BIOS版本有一定关系我之前是1.10.1，现在已经升到最新的1.11.0。

**Comment by jardenliu** [comment]
不一点有关吧，我还有1.9.1的BIOS文件，要发给你试试吗？

**Comment by jardenliu** [comment]
难以描述，你试试呗
