### ISSUE TITLE
能否通过调高温控临界温度来获取更好的静音效果？

### ISSUE THREAD

**Issue by zzzqqqhhh** [jardenliu/XPS15-9560-Mojave#15]
### 问题描述
大神能否通过这个帖子（http://bbs.pcbeta.com/viewthread-1037700-1-430.html 14楼）所描述的方法来实现风扇在55度以上才启动？Win10下用Dell Power command设置静音模式一般也是在55度后启动风扇的，感觉目前黑苹果下40度就启动风扇有点低了。
本人愿意当小白鼠试验😄

### 贴上你的配置
1. CPU：7300HQ
2. BIOS:1.12
3. 屏幕分辨率:4K

#### 以下根据问题选填或补充
1. 硬盘：256
2. 内存：8
3. WIFI网卡:DW1830
...
https://www.hackintosh-forum.de/forum/thread/35412-l%C3%BCftersteuerung-in-macos-beim-xps15/?pageNo=1

https://www.hackintosh-forum.de/forum/thread/27520-temperaturabh%C3%A4ngige-l%C3%BCftersteuerung-f%C3%BCr-lenovo-t6x-t4xx-m%C3%B6glicherweise-auch-ande/?postID=241003#post241003
这2个帖子讲的更详细点，但却是德语的……

**Comment by jardenliu** [comment]
我的风扇不怎么会转，平时温度也只是40°左右
