### ISSUE TITLE
Mojave的安装步骤跟HighSierra的步骤是否有不同？

### ISSUE THREAD

**Issue by ToCHONG** [jardenliu/XPS15-9560-Mojave#16]
配置跟你的一致，网卡是DW1560

**Comment by BillTaozi** [comment]
我是全新安装的10.14，用的的是您提供CLOVER里的所有驱动BIOS用的是最新版的，设置完全按照教程里关于BIOS的教程设置的，其他问题没发现，就是开机第二阶段花屏，一闪而过，虽然不影响进入系统和使用，就是问问您这边有没有好的解决办法，网上安装的那个驱动，导致系统进不了，无限循环重启！

发送自 Windows 10 版邮件应用

发件人: 流君酱
发送时间: 2018年11月8日 17:56
主题: Re: [jardenliu/XPS15-9560-Mojave] Mojave的安装步骤跟HighSierra的步骤是否有不同？ (#16)

Closed #16.
