### ISSUE TITLE
Mojave 10.12.1 开机第二阶段花屏

### ISSUE THREAD

**Issue by BillTaozi** [jardenliu/XPS15-9560-Mojave#17]
关于开机第二阶段花屏问题有解决的补丁吗？看了其他的HD 4000有相关补丁，HD630最新系统好像没有帖子；

**Comment by jardenliu** [comment]
12.1？

**Comment by BillTaozi** [comment]
写错了，10.14.1 其他没啥问题，就是开机第二阶段花屏或一闪，看了网上的教程，有IntelGraphicsFixup.kext v1.2.3 解决黑苹果核心显卡花屏 可是按照教程放在clover other 里，开机进不了系统，无限重启，无奈只好删除了
