### ISSUE TITLE
关于触摸板的问题

### ISSUE THREAD

**Issue by ToCHONG** [jardenliu/XPS15-9560-Mojave#18]
拖动只能按下不能轻点两下拖动吗？我记得以前即使不能正常驱动的触摸板也可以。还有launchpad和显示桌面的手势经常不行，是姿势不对还是bug？

**Comment by jardenliu** [comment]
建议购买macbook 以获得更好的体验

**Comment by ToCHONG** [comment]
拖动已解决，在accessibility中的trackpad选项中enable dragging就OK了

**Comment by BillTaozi** [comment]
启动辅助功能里的三至拖移就可以解决拖动问题了，看图
<img width="1680" alt="2018-11-12 12 34 44" src="https://user-images.githubusercontent.com/35515198/48327032-80ba7480-e677-11e8-82cb-10ff5989c5fb.png">
