### ISSUE TITLE
音频问题

### ISSUE THREAD

**Issue by jizongFox** [jardenliu/XPS15-9560-Mojave#19]
### 问题描述
...

### 贴上你的配置
1. CPU：7700
2. BIOS: 1.12.1 
3. 屏幕分辨率: 4K

#### 以下根据问题选填或补充
1. 插着耳机有声音 而取下耳机后，音量按键消失，无法播放
...

**Comment by jizongFox** [comment]
Only this bug has been found for my 9560 computer. Others seem to work very well.

**Comment by jardenliu** [comment]
Did you install alcplufix?

**Comment by jizongFox** [comment]
If you mean the install.sh in the post-install folder. Yes, several times. It doesn’t work.

**Comment by jardenliu** [comment]
Have you test it in windows before?

**Comment by jizongFox** [comment]
This issue has been solved by installing install双击自动安装.command instead of install.sh. I close it. Thanks very much.
