### ISSUE TITLE
10.13.6升级卡白苹果

### ISSUE THREAD

**Issue by Skilling-Kiss** [jardenliu/XPS15-9560-Mojave#2]
clover也换了，昨天晚上直接在App Store里升级，重启就一直白苹果了，不知道为什么

**Comment by jardenliu** [comment]
如果是从码云下载的，请重新下载，刚刚更新

**Comment by BillTaozi** [comment]
升级10.14是用你的other里的驱动直接替换原来的然后直接升级成功后再把自己原先的替换回来吗，之前我在10.13小更新我一直都是这样的都是这么做的，现在10.13-10.14这样做可以吗，我还没试呢、

**Comment by jardenliu** [comment]
升级成功了为什么要替换回去呢

**Comment by BillTaozi** [comment]
ok，明白，谢谢啊
