### ISSUE TITLE
mac 蓝牙丢失

### ISSUE THREAD

**Issue by BillTaozi** [jardenliu/XPS15-9560-Mojave#20]
今天我的mac蓝牙忽然就丢失了，开机关机好几次没有搜到蓝牙，设置里没有了，关于本机，系统信息报告里也没有了，之前是有的，这个怎么解决呀？
<img width="1680" alt="2018-11-15 16 53 00" src="https://user-images.githubusercontent.com/35515198/48541416-87efb580-e8f7-11e8-8816-e36b4ea31ff0.png">
<img width="1680" alt="2018-11-15 16 55 55" src="https://user-images.githubusercontent.com/35515198/48541421-88884c00-e8f7-11e8-8fda-5ec61189a6ed.png">

**Comment by jardenliu** [comment]
关机再开机，不要重启

**Comment by BillTaozi** [comment]
我回到win10系统下查看了一下蓝牙，也发现蓝牙无法使用，不会是蓝牙坏了吧，用鲁大师检测硬件，发现蓝牙打红叉，完蛋了，蓝牙怎么会突然坏了，奇怪了去！

**Comment by BillTaozi** [comment]
按照jardenliu方法，关机再开机，蓝牙又回来，万幸不是蓝牙模块坏了；

**Comment by jardenliu** [comment]
关机再开机和重启是有差别的
