### ISSUE TITLE
Caps Lock键不能切换中英文输入法……

### ISSUE THREAD

**Issue by zzzqqqhhh** [jardenliu/XPS15-9560-Mojave#21]
### 问题描述
RT...

### 贴上你的配置
1. CPU：
2. BIOS:
3. 屏幕分辨率:

#### 以下根据问题选填或补充
1. 硬盘：
2. 内存：
3. WIFI网卡:
...

**Comment by jardenliu** [comment]
这是没得办法的事情，会有冲突
