### ISSUE TITLE
请教一下触摸板驱动更新

### ISSUE THREAD

**Issue by ToCHONG** [jardenliu/XPS15-9560-Mojave#22]
经对比发现现在用的是2.0.1而最新的是2.1.4，触摸板和触摸屏驱动是否有必要更新？如果要更新的话，是否需要像VooDooI2C的教程一样修改dsdt还是直接复制到clover即可？望指教，谢谢

**Comment by jardenliu** [comment]
不推荐升级，升级有点bug。至于为什么是2.0.1，解释起来有点麻烦
