### ISSUE TITLE
更新14.1之后99%几率无限重启

### ISSUE THREAD

**Issue by Karel190** [jardenliu/XPS15-9560-Mojave#23]
Hi我是XPS9560 4K版本，之前使用Mojave您的配置一切正常，上次升级之后，就会在进入系统的时候自动重启，重试很多次后还是有几率进入系统，请问这个是什么原因呢？我直接用的你提供的clover和kext，没有加入任何其它东西。

**Comment by BillTaozi** [comment]
你看看的BIOS是否完全按照这个来进行设置的，我的之前升级也遇到了同样的问题，进行相关设置后就没事了
<img width="1680" alt="2018-11-23 14 07 38" src="https://user-images.githubusercontent.com/35515198/48930131-6612b600-ef29-11e8-8495-23c6f1425032.png">

**Comment by BillTaozi** [comment]
xps 15 9560 进入BIOS的方法，开机见到dell的logo是按F12，然后选择BIOS设置，按照下图完整设置就好！
<img width="1680" alt="2018-11-23 14 07 38" src="https://user-images.githubusercontent.com/35515198/48930200-e20cfe00-ef29-11e8-9f23-cc94579cf690.png">

**Comment by Karel190** [comment]
@BillTaozi 感谢回复，你的办法我试了没用，经过排查，我需要在EFI里面删除AirportBrcmFixup.kext，这样才能进去。不知道为什么，很奇怪。
