### ISSUE TITLE
关于触摸板体验优化

### ISSUE THREAD

**Issue by BillTaozi** [jardenliu/XPS15-9560-Mojave#24]
mac 10.14 在xps 15 9560 上有没有可能在目前的触摸体验上进一步的优化，捏拢拇指和三指开启 启动台和张开拇指和三指调出桌面，这两个动作目前成功率比较低，当然这个和mac 的触摸板肯定没法比，但从驱动优化的角度来讲是否可以实现优化体验效果的目的呢？

**Comment by zzzqqqhhh** [comment]
还有打字很容易误触

**Comment by BillTaozi** [comment]
这个我倒是没有，现在的这个触摸板驱动比在10.13的时候已经强了很多，支持原生态的手势，就是个别手势不灵

**Comment by jizongFox** [comment]
还有打字很容易误触

**Comment by jardenliu** [comment]
触控板驱动来自于这里https://github.com/alexandred/VoodooI2C     误触无解
