### ISSUE TITLE
USB-C Problems

### ISSUE THREAD

**Issue by LeLunZ** [jardenliu/XPS15-9560-Mojave#26]
Hi.
USB-C hotplug is not working. Only if USB-C device was plugged in between clover start and Mac OS boot.
Tried with a Dell USB-C Adapter and a usb-c SSD.

If the adapter is working I am getting a kernel panic when plugged in a second Display with HDMI over the Native port while trying to plug in a third monitor via the USB-C Adapter.

Any ways to fix?

*** Panic Report ***
panic(cpu 0 caller 0xffffff8011cda1ed): Kernel trap at 0xffffff7f9458938b, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0x00000000000001dc, CR3: 0x000000001f010000, CR4: 0x00000000003626e0
RAX: 0x40ea56b7e04100ee, RBX: 0x0000000000000002, RCX: 0x0000000000000001, RDX: 0x0000000000000001
RSP: 0xffffff81f90c3e30, RBP: 0xffffff81f90c3e90, RSI: 0x0000000000000001, RDI: 0x0000000000000002
R8:  0x0000000000000003, R9:  0xffffff8043060420, R10: 0x0000000000000000, R11: 0x0000000000000000
R12: 0x0000000000000002, R13: 0x0000000000000000, R14: 0xffffff81b7762000, R15: 0x0000000000000000
RFL: 0x0000000000010246, RIP: 0xffffff7f9458938b, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x00000000000001dc, Error code: 0x0000000000000000, Fault CPU: 0x0, PL: 0, VF: 1

Backtrace (CPU 0), Frame : Return Address
0xffffff81f90c3900 : 0xffffff8011baeafd mach_kernel : _handle_debugger_trap + 0x48d
0xffffff81f90c3950 : 0xffffff8011ce85a3 mach_kernel : _kdp_i386_trap + 0x153
0xffffff81f90c3990 : 0xffffff8011cd9fca mach_kernel : _kernel_trap + 0x4fa
0xffffff81f90c3a00 : 0xffffff8011b5bca0 mach_kernel : _return_from_trap + 0xe0
0xffffff81f90c3a20 : 0xffffff8011bae517 mach_kernel : _panic_trap_to_debugger + 0x197
0xffffff81f90c3b40 : 0xffffff8011bae363 mach_kernel : _panic + 0x63
0xffffff81f90c3bb0 : 0xffffff8011cda1ed mach_kernel : _kernel_trap + 0x71d
0xffffff81f90c3d20 : 0xffffff8011b5bca0 mach_kernel : _return_from_trap + 0xe0
0xffffff81f90c3d40 : 0xffffff7f9458938b com.apple.driver.AppleIntelKBLGraphicsFramebuffer : __ZN31AppleIntelFramebufferController20invokeHotplugHandlerEj + 0x4e1
0xffffff81f90c3e90 : 0xffffff7f94568930 com.apple.driver.AppleIntelKBLGraphicsFramebuffer : __ZN31AppleIntelFramebufferController18SWInterruptHandlerEP8OSObjectP22IOInterruptEventSourcei + 0x1b2
0xffffff81f90c3ed0 : 0xffffff80122575dd mach_kernel : __ZN22IOInterruptEventSource12checkForWorkEv + 0x13d
0xffffff81f90c3f30 : 0xffffff8012255672 mach_kernel : __ZN10IOWorkLoop15runEventSourcesEv + 0x1e2
0xffffff81f90c3f70 : 0xffffff8012254bfc mach_kernel : __ZN10IOWorkLoop10threadMainEv + 0x2c
0xffffff81f90c3fa0 : 0xffffff8011b5b0ce mach_kernel : _call_continuation + 0x2e
      Kernel Extensions in backtrace:
         com.apple.driver.AppleIntelKBLGraphicsFramebuffer(12.0.4)[0E71EF1C-A01B-354E-987D-476E0029C6ED]@0xffffff7f9453b000->0xffffff7f9475ffff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[7EA30FDD-A2FB-390F-99DD-42BC19691BB4]@0xffffff7f92495000
            dependency: com.apple.iokit.IOACPIFamily(1.4)[99A8A054-9F64-3FB8-BB1D-5973F8AB04A1]@0xffffff7f92bb3000
            dependency: com.apple.iokit.IOAcceleratorFamily2(404.2.2)[FA92A03C-F113-384A-9B1F-B2C52DE7F4D2]@0xffffff7f93cf7000
            dependency: com.apple.iokit.IOReportFamily(47)[75A625B5-0DEB-343A-A723-9D72533F098C]@0xffffff7f930e7000
            dependency: com.apple.AppleGraphicsDeviceControl(3.28.4)[400C2E21-0880-36D7-AC5E-6B9BC885F158]@0xffffff7f93079000
            dependency: com.apple.iokit.IOGraphicsFamily(530.14)[C5617AC3-A68D-36CE-AC22-7C7C81318961]@0xffffff7f92d60000

**Comment by jardenliu** [comment]
This is really a problem, but I dont konw how to fix it~
