### ISSUE TITLE
雷电接口热插拔好像可以了

### ISSUE THREAD

**Issue by shawnchan2014** [jardenliu/XPS15-9560-Mojave#28]
### 问题描述
看到别的帖子里面显示雷电接口热插拔fixed了，楼主可以update一下
https://www.insanelymac.com/forum/topic/336203-xps-9560-mojave-guide/
https://www.tonymacx86.com/threads/in-progress-ssdt-for-thunderbolt-3-hotplug.248784/

### 贴上你的配置
1. CPU：
2. BIOS:
3. 屏幕分辨率:

#### 以下根据问题选填或补充
1. 硬盘：
2. 内存：
3. WIFI网卡:
...

**Comment by jardenliu** [comment]
没设备，改了也测试不了

**Comment by carking** [comment]
https://www.tonymacx86.com/threads/guide-dell-xps-9560-mojave-virtualsmc-i2c-trackpad-clover-uefi-hotpatch.263567/
推荐这个efi
