### ISSUE TITLE
电池percentage显示不准确

### ISSUE THREAD

**Issue by shawnchan2014** [jardenliu/XPS15-9560-Mojave#29]
### 问题描述
用的是virtual smc那个配置。实际电池没有充满，但是却显示100%电量，不知道是不是virtual smc的问题因为在别的帖子里面看到说virtual smc电池显示有时候会奇怪

### 贴上你的配置
1. CPU：i7 7700
2. BIOS: 1.12
3. 屏幕分辨率: 4k

#### 以下根据问题选填或补充
1. 硬盘：512 toshiba
2. 内存：16g
3. WIFI网卡: dw1560
...

**Comment by jardenliu** [comment]
virtual smc的电量就是超级不准
