### ISSUE TITLE
用的github的clover，依然出错

### ISSUE THREAD

**Issue by Skilling-Kiss** [jardenliu/XPS15-9560-Mojave#3]
因为原来的版本出问题了，所以我重新安装了macos，但是安装正式版的过程中会出错，本来用的黑锅小兵的，但是换了其他人做好的mojave也不行，不知道是哪出问题了

**Comment by BillTaozi** [comment]
还是等大神的具体教程吧，我是不敢自己弄，现在停留在10.13.6不敢动呢

**Comment by jardenliu** [comment]
@Skilling-Kiss 提供一下你的电脑的具体配置参数，尤其是硬盘牌子型号，已经BIOS版本号

**Comment by Skilling-Kiss** [comment]
已经搞定了，原来是因为U盘的问题，换了个U盘就可以了，我的配置和你一样，都是4KI716G

**Comment by jardenliu** [comment]
好吧
