### ISSUE TITLE
选择睡眠后 无法使用键盘唤醒 

### ISSUE THREAD

**Issue by liqiantu** [jardenliu/XPS15-9560-Mojave#30]
### 问题描述
选择睡眠后 无法使用键盘唤醒 
按电源按钮或者按下触控板可以唤醒系统
还遇到选择睡眠后，屏幕立即熄灭，但是电源按钮指示灯与键盘背光过大概半分钟才熄灭

上述问题在选择合盖睡眠与开盖唤醒都没遇到，只有在点击睡眠的时候才遇到

1. CPU：i5 7300
2. BIOS: 1.11.0
3. 屏幕分辨率: 4k

#### 以下根据问题选填或补充
1. 硬盘：
2. 内存：
3. WIFI网卡:
...

**Comment by jardenliu** [comment]
正常
