### ISSUE TITLE
从10.13最终配置顺利更新到10.14，然后更换成这个项目的配置就卡代码界面了

### ISSUE THREAD

**Issue by yasuharaema** [jardenliu/XPS15-9560-Mojave#31]
### 问题描述
从10.13最终配置顺利更新到10.14，然后更换成这个项目的配置就卡代码界面了
我是先删除了10.13的最终配置，然后把这个项目的配置放了进去，结果就卡代码界面了Orz求助
卡在代码界面图片：http://miao.su/images/2019/01/06/_201901060946225b247.jpg
我的原配置可正常进入：链接: https://pan.baidu.com/s/1sJRuC9RQSVPB0mp0wZVdNw 提取码: 28ex 

### 贴上你的配置
1. CPU：i7-7700HQ
2. BIOS:
3. 屏幕分辨率:4K

#### 以下根据问题选填或补充
1. 硬盘：东芝THN5N51T02DUK 1TSSD
2. 内存：32gb
3. WIFI网卡: DW1830
...

**Comment by yasuharaema** [comment]
对了，我用的是VirtualSmc版本
我也不知道为什么我每次更新配置就出现这样的问题。。上次10.13的最终配置还是多次请教jardenliu才更新成功Orz

**Comment by yasuharaema** [comment]
排查了一下午，用master版本就顺利进去了
VirtualSmcba版本我剔除掉USB那个后也可以顺利进去，但是VirtualSmc版本从开机到进入系统至少需要5分钟，不知道jardenliu会不会这样？

**Comment by BillTaozi** [comment]
VirtualSmcba目前还不成熟，至少还不稳定，还是不要用了，原先的就挺好！

**Comment by yasuharaema** [comment]
已经用fakeSmc了
就是昨晚发现，每次开机用了一段时间后系统里的程式就会出现无响应，强制关闭之后就再也打不开
然后想关机重启，连关机都关不了了...很苦恼，也查不出原因来
求助

**Comment by yasuharaema** [comment]
对了还想请教一下，jardenliu的4k屏一键开启hidpi是用哪个配置？1080P还是手动输入4k分辨率？

**Comment by BillTaozi** [comment]
没有发现，一切正常。

发送自 Windows 10 版邮件应用

发件人: yasuharaema
发送时间: 2019年1月7日 22:30
收件人: jardenliu/XPS15-9560-Mojave
抄送: BIllTaozi; Mention
主题: Re: [jardenliu/XPS15-9560-Mojave]=?UTF-8?Q?_=E4=BB=8E10.13=E6=9C=80=E7=BB=88=E9=85=8D=E7=BD=AE=E9=A1=BA=E5=88=A9=E6=9B=B4=E6=96=B0=E5=88=B010.14=EF=BC=8C=E7=84=B6=E5=90=8E=E6=9B=B4=E6=8D=A2=E6=88=90=E8=BF=99=E4=B8=AA=E9=A1=B9=E7=9B=AE=E7=9A=84=E9=85=8D=E7=BD=AE=E5=B0=B1=E5=8D=A1=E4=BB=A3=E7=A0=81=E7=95=8C=E9=9D=A2=E4=BA=86?==?UTF-8?Q?_=28#31=29?=

@BillTaozi 今晚感觉打开任何文件都会有一秒左右的延迟，你那边会吗？不是预览，是打开

**Comment by yasuharaema** [comment]
我决定重装了，头疼=-=

**Comment by BillTaozi** [comment]
嗯，重装可以彻底解决你的问题，只是软件安装比较麻烦，AE PS 等视频编辑软件需要重装的同时各种插件需要重新部署，所以一般不成熟的更新不要乱用；

发送自 Windows 10 版邮件应用

发件人: yasuharaema
发送时间: 2019年1月8日 10:06
收件人: jardenliu/XPS15-9560-Mojave
抄送: BIllTaozi; Mention
主题: Re: [jardenliu/XPS15-9560-Mojave]=?UTF-8?Q?_=E4=BB=8E10.13=E6=9C=80=E7=BB=88=E9=85=8D=E7=BD=AE=E9=A1=BA=E5=88=A9=E6=9B=B4=E6=96=B0=E5=88=B010.14=EF=BC=8C=E7=84=B6=E5=90=8E=E6=9B=B4=E6=8D=A2=E6=88=90=E8=BF=99=E4=B8=AA=E9=A1=B9=E7=9B=AE=E7=9A=84=E9=85=8D=E7=BD=AE=E5=B0=B1=E5=8D=A1=E4=BB=A3=E7=A0=81=E7=95=8C=E9=9D=A2=E4=BA=86?==?UTF-8?Q?_=28#31=29?=

我决定重装了，头疼=-=

**Comment by yasuharaema** [comment]
昨晚甚至连PSAE都打不开，删了想重装结果安装包也打不开，但是其他又正常
我又没干嘛很奇怪了，就只是从10.13.4升级上来而已
还是重装省事
