### ISSUE TITLE
Netflix & Itunes Problem

### ISSUE THREAD

**Issue by LeLunZ** [jardenliu/XPS15-9560-Mojave#33]
### 问题描述
When starting a Video on Netflix in safari I get an error (in chrome + Firefox is it working): S7363-1260-FFFFD089
And when starting a movie in iTunes I get an HDCP Error.
Youtube is working.

Got the same problem, is there a fix?

### 贴上你的配置
1. CPU：i7-7700HQ
2. BIOS: 1.9.4
3. 屏幕分辨率:  1920x1080

#### 以下根据问题选填或补充
1. 硬盘：SK hynix 512 GB
2. 内存：2x8GB Kingston
3. WIFI网卡: DW1830

**Comment by LeLunZ** [comment]
Yeah but I got Whatevergreen in my clover/kexts/other folder

**Comment by jardenliu** [comment]
you can open a new issue in Whatevergreen repo
