### ISSUE TITLE
请求关于蓝牙的设置问题

### ISSUE THREAD

**Issue by BillTaozi** [jardenliu/XPS15-9560-Mojave#34]
### 问题描述
关于蓝牙设置问题------在Windows下的下的设置问题；

### 贴上你的配置
1. CPU：英特尔处理器七代  i7 7700HQ  显卡1050
2. BIOS:1.12.1
3. 屏幕分辨率:1080

#### 以下根据问题选填或补充
1. 硬盘：KXG50ZNV256G NVMe TOSHIBA 256GB+Samsung SSD 850 EVO 250GB
2. 内存：16G（8G * 2）2400MHz DDR4
3. WIFI网卡:博通D1830
4.KXG50ZNV256G NVMe TOSHIBA 256GB为驱动0 装win10；Samsung SSD 850 EVO 250GB 
5、细节如下图；
![qq 20190118013li](https://user-images.githubusercontent.com/35515198/51360303-16560280-1b06-11e9-9263-4e4582f5ca87.jpg)
![_20190118014755](https://user-images.githubusercontent.com/35515198/51360333-2e2d8680-1b06-11e9-8512-1ba771f0bd97.jpg)

**Comment by yasuharaema** [comment]
是网络适配器那个DW1830

**Comment by BillTaozi** [comment]
> 是网络适配器那个DW1830

谢谢你的回复，可是右键--属性--高级--下面是什么呢？我这里没有蓝牙合作选项呀？如下图所示
![qq 20190118015309_li](https://user-images.githubusercontent.com/35515198/51360741-e60f6380-1b07-11e9-9fc8-f3477991cfa6.jpg)

**Comment by yasuharaema** [comment]
属性->高级->Bluetooth Cooperation（前面Bluetooth一致，后边可能不同），设置为disable

**Comment by BillTaozi** [comment]
> 属性 - >高级 - > Bluetooth Cooperation（前面蓝牙一致，后边可能不同），设置为禁用

是这样吗？如果禁用了，win10下的蓝牙还可以用吗？
![_20190118020608_li](https://user-images.githubusercontent.com/35515198/51361045-23c0bc00-1b09-11e9-947d-e2e9b9523e16.jpg)

**Comment by yasuharaema** [comment]
可以用，这个只是让蓝牙不干扰wifi而已

**Comment by BillTaozi** [comment]
> 可以用，这个只是让蓝牙不干扰无线网络而已

Bluetooth Cooperation没有这个选项呀，我看到的是Bluetooth Collaboration选项，是这个吗？

**Comment by yasuharaema** [comment]
（前面Bluetooth一致，后边可能不同）

**Comment by BillTaozi** [comment]
Bluetooth Cooperation

> （前面蓝牙一致，后边可能不同）

![qq 20190118021628_li](https://user-images.githubusercontent.com/35515198/51361349-68008c00-1b0a-11e9-8b67-590221202e07.jpg)
是这个吧？

**Comment by BillTaozi** [comment]
> （前面Bluetooth一致，后边可能不同）

好的，已经解决了，谢谢啊，你的机器启动时会卡在白苹果logo处吗，出现几率挺大的，我新装的机器频繁出现，烦死了；
