### ISSUE TITLE
开机卡在白苹果logo出进不系统怎么办？？？

### ISSUE THREAD

**Issue by BillTaozi** [jardenliu/XPS15-9560-Mojave#36]
### 问题描述
...开机卡在白苹果logo地方不动，一般要十几分钟才能进入界面，或者强制关机重启，出现频率50％ 

### 贴上你的配置
1. CPU：英特尔处理器七代  i7 7700HQ  显卡1050
2. BIOS:1.12.1
3. 屏幕分辨率:1080

#### 以下根据问题选填或补充
1. 硬盘：KXG50ZNV256G NVMe TOSHIBA 256GB+Samsung SSD 850 EVO 250GB
2. 内存：16G（8G * 2）2400MHz DDR4
3. WIFI网卡:博通D1830
4.KXG50ZNV256G NVMe TOSHIBA 256GB装Mac；Samsung SSD 850 EVO 250GB win10系统；
5、刚刚装好时偶尔出现卡住的现象，最近比较频繁，只要卡住，在等待十几分钟后成功进入系统，发现蓝牙丢失；关机重启，正常进入，蓝牙正常；
6、具体如下图所示：
![wechatimg2](https://user-images.githubusercontent.com/35515198/51510232-399aed80-1e37-11e9-9d2d-6c61af87f00d.jpeg)

![2019-01-22 5 18 16](https://user-images.githubusercontent.com/35515198/51524768-c8c0f900-1e69-11e9-89d3-fb28e41121d2.png)

**Comment by BillTaozi** [comment]
大神救助啊，这个问题好久了，各种百度，无解呀！！

**Comment by jardenliu** [comment]
下载`https://raw.githubusercontent.com/daliansky/XiaoMi-Pro/master/EFI/CLOVER/drivers64UEFI/AptioMemoryFix-64.efi`,

把CLOVER/drivers64UEFI/OsxAptioFix2Drv-64.efi删除后，把`AptioMemoryFix-64.efi`放到`CLOVER/drivers64UEFI`里面

**Comment by BillTaozi** [comment]
> 下载`https://raw.githubusercontent.com/daliansky/XiaoMi-Pro/master/EFI/CLOVER/drivers64UEFI/AptioMemoryFix-64.efi`,
> 
> 把CLOVER/drivers64UEFI/OsxAptioFix2Drv-64.efi删除后，把`AptioMemoryFix-64.efi`放到`CLOVER/drivers64UEFI`里面

谢谢，已经解决了，感谢帮助了！！！！
