### ISSUE TITLE
Mac启动台多了些网站图标，点击可以打开连接，但不想要他们，如何删除？

### ISSUE THREAD

**Issue by BillTaozi** [jardenliu/XPS15-9560-Mojave#37]
Mac启动台多了这些网站，删除不掉，如何处理？？
![2019-01-23 11 29 01](https://user-images.githubusercontent.com/35515198/51581305-78e24080-1f02-11e9-8be1-8d66f23c7335.png)
![2019-01-23 11 29 17](https://user-images.githubusercontent.com/35515198/51581306-797ad700-1f02-11e9-9947-8054b84dafb9.png)

**Comment by jardenliu** [comment]
系统操作问题，不作答谢谢
