### ISSUE TITLE
Mac os Mojave 10.14.3 安装U盘问题

### ISSUE THREAD

**Issue by BillTaozi** [jardenliu/XPS15-9560-Mojave#39]
xps 15 9560 1080 的，问题是u盘启动安装卡在下面如图：
![wechatimg3](https://user-images.githubusercontent.com/35515198/53629784-708bcc80-3c49-11e9-9c43-3abece42496f.jpeg)

**Comment by Princezhu** [comment]
请问你问题解决了吗？我也遇到同样的问题 555

**Comment by BillTaozi** [comment]
没有啊，找了很多资料，没有关于这个方面的，我以为就我自己出现了这个情况，看来不是个例啊！

**Comment by BillTaozi** [comment]
没有啊，找了很多资料，没有关于这个方面的，我以为就我自己出现了这个情况，看来不是个例啊！

**Comment by BillTaozi** [comment]
有谁会解决这个问题呀？

**Comment by BillTaozi** [comment]
问题已经搞定，就是把安装mac 的硬盘全部格式化掉重新分区，全新安装，否则不行；

**Comment by BillTaozi** [comment]
> 请问你问题解决了吗？我也遇到同样的问题555
问题已经搞定，就是把安装mac的硬盘全部格式化掉重新分区，全新安装，否则不行;
