### ISSUE TITLE
制作安装u盘遇到问题求救

### ISSUE THREAD

**Issue by BillTaozi** [jardenliu/XPS15-9560-Mojave#40]
u盘驱动是用你的clover下载驱动 u盘制作好了启动提示错误，卡在  I nitialized /dev/rdisk6 as a 5MB case-insensitive HFS Plus volume

**Comment by BillTaozi** [comment]
u盘制作好了启动提示错误，卡在  I nitialized /dev/rdisk6 as a 5MB case-insensitive HFS Plus volume
关于这个问题在黑果小兵 博主的qq群里也没有人会，目前无法解决，需求大师帮助！

**Comment by jardenliu** [comment]
same as #39
