### ISSUE TITLE
按照教程装上mojave之后Windows 10 下独显问题

### ISSUE THREAD

**Issue by rannj** [jardenliu/XPS15-9560-Mojave#41]
### 问题描述
Windows 10 下独显显示连接，也可以装驱动，但设置某应用为用独显开启之后（比如游戏等调用显卡资源多的应用），虽然gpu状态显示该应用已经调用了独显，但应用会卡死。想问一下您有没有出现相关问题，目前不知道猜测是bios设置引起的。

### 贴上你的配置
1. CPU：i7-7700HQ
2. BIOS: 1.12.1
3. 屏幕分辨率: 3840*2160

#### 以下根据问题选填或补充
1. 硬盘：PC300 NVMe SK hynix 512GB
2. 内存：海力士8G*2
3. WIFI网卡:  未更换

**Comment by jardenliu** [comment]
可以使用win10 EFI启动 对比效果
