### ISSUE TITLE
无法更新升级10.14.4

### ISSUE THREAD

**Issue by parchrome** [jardenliu/XPS15-9560-Mojave#42]
### 问题描述
10.14.3无法更新升级10.14.4

### 贴上你的配置
1. CPU：7700HQ
2. BIOS:
3. 屏幕分辨率: 4K

#### 以下根据问题选填或补充
1. 硬盘：
2. 内存：
3. WIFI网卡:DW1830
...

**Comment by jardenliu** [comment]
更新CLOVERX64.efi到新版本
