### ISSUE TITLE
Upgrade feasibility

### ISSUE THREAD

**Issue by jizongFox** [jardenliu/XPS15-9560-Mojave#43]
### 问题描述
I would like to ask if it is okay to upgrade the system to 10.14.4. Actually I am using 10.14.1 and it works perfectly.

### 贴上你的配置
1. CPU：7700HQ
2. BIOS:
3. 屏幕分辨率: 4K

#### 以下根据问题选填或补充
1. 硬盘：
2. 内存：
3. WIFI网卡:
...

**Comment by jardenliu** [comment]
As for my laptop, it work fine. but somebody told me that, they try to upgrade system to 10.14.4 and failed. If you dont have to upgrade system, 10.14.1 is better than 10.14.4 before we know what cause upgrade failed.

**Comment by jizongFox** [comment]
I have successfully upgraded to 14.1.4. I will let you know if I find something wrong.

**Comment by jardenliu** [comment]
okay :D

**Comment by jizongFox** [comment]
Could you please tell me how to disable the touchpad (whether you have a mouse or not). I followed the instruction: https://www.tekrevue.com/tip/disable-macbook-trackpad/ , apparently, it doesn't work.

**Comment by jardenliu** [comment]
why do you wanna disable it ?

**Comment by jizongFox** [comment]
Due to the fact that the touchpad disturbs typing frequently.

**Comment by LeLunZ** [comment]
> As for my laptop, it work fine. but somebody told me that, they try to upgrade system to 10.14.4 and failed. If you dont have to upgrade system, 10.14.1 is better than 10.14.4 before we know what cause upgrade failed.

Could it be that the update failed because Clover wasn't up to date? (That was my problem)

**Comment by jardenliu** [comment]
![image](https://user-images.githubusercontent.com/15191056/55172059-67dcd680-51b4-11e9-947d-7f1c74d3c5ee.png)
I forgot the option name in English. Cancel this option, then  typing will be smoother

**Comment by jizongFox** [comment]
> ![image](https://user-images.githubusercontent.com/15191056/55172059-67dcd680-51b4-11e9-947d-7f1c74d3c5ee.png)
> I forgot the option name in English. Cancel this option, then typing will be smoother

Thanks very much for your reply!!

**Comment by jizongFox** [comment]
The computer fails after updating xcode. Do you have any suggestion?

**Comment by jardenliu** [comment]
I have successfully upgraded to xcode 10.2. Maybe you can try to remove xcode, and reinstall it

**Comment by jizongFox** [comment]
How can I remove the Xcode without entering the system?

**Comment by jardenliu** [comment]
you cant enter system? what error shown?
