### ISSUE TITLE
电量显示不准，掉电快

### ISSUE THREAD

**Issue by aj0wz** [jardenliu/XPS15-9560-Mojave#44]
### 问题描述

用的10.14.4，电量百分比显示不准，但点在电池管理那里是准的。掉电极快，虽然是小电池但明显比win10掉电快很多，放着不动两三分钟掉1%电，最高亮度少两格。大写锁定键有点冲突，触摸板偶尔会突然不听使唤。
### 贴上你的配置
1. CPU：7700hq
2. BIOS:最新版本
3. 屏幕分辨率:1080p

#### 以下根据问题选填或补充
1. 硬盘：西数sn750 500G+三星860evo 500G
2. 内存：海力士 2*4
3. WIFI网卡:killer
...

**Comment by BillTaozi** [comment]
我也是，电量掉的很快

**Comment by jardenliu** [comment]
用VirtualSmc的电池显示会准一点

**Comment by ShiningXu** [comment]
西数sn750 非常费电，我换成intel760p 后待机功耗少了将近3W
