### ISSUE TITLE
Speed up CPU

### ISSUE THREAD

**Issue by jizongFox** [jardenliu/XPS15-9560-Mojave#45]
### 问题描述
Hi, could you please tell me how to disable the frequency decrease of CPU as it usually works on 1.9GHz-3GHz and I want it to work with all speed (2.8GHz or more)

### 贴上你的配置
1. CPU：7700HQ
2. BIOS:
3. 屏幕分辨率: 4K

#### 以下根据问题选填或补充
1. 硬盘：
2. 内存：
3. WIFI网卡: 1830
...

**Comment by jardenliu** [comment]
Intel CPU auto turbo boost

**Comment by jizongFox** [comment]
But How to disable that?
