### ISSUE TITLE
mac os  Mojave 10.14.4 睡眠后音频无声问题

### ISSUE THREAD

**Issue by BillTaozi** [jardenliu/XPS15-9560-Mojave#46]
### 问题描述
...

### 贴上你的配置
1. CPU：i7 7700hq 
2. BIOS:12.1
3. 屏幕分辨率:

#### 以下根据问题选填或补充
1. 硬盘：
2. 内存：
3. WIFI网卡:
...
u盘全新安装的mac os Mojave 10.14.4 发现睡眠后无声，请问你有遇到这个问题吗？

**Comment by jimyth01** [comment]
我碰到了，升级了lilu applealc 和whatevergreen之后 好了

**Comment by BillTaozi** [comment]
> 我碰到了，升级了lilu applealc和whatevergreen之后好了

这两个驱动我是下载我们这个网站里跟新的呀

**Comment by jimyth01** [comment]
那我就不知道了AppleALC 我用的1.3.6  lilu 1.3.5  WhateverGreen 1.2.7

**Comment by BillTaozi** [comment]
> 那我就不知道了AppleALC我用的1.3.6 lilu 1.3.5 WhateverGreen 1.2.7
我从黑苹果乐园网站下载最新版的，跟你的一样，解决问了，另外我一只有一个问题，就是外接的USB U盘或外接的USB硬盘经常性的说硬盘退出有错误，合上屏幕WiFi断掉，硬盘自己退出，说什么推出错误的，我们这里用的是USBPower.kext ，黑果小兵用USBInjectAll.kext，这有什么区别呀？
