### ISSUE TITLE
求助，升级10.14.4后引导丢失

### ISSUE THREAD

**Issue by yasuharaema** [jardenliu/XPS15-9560-Mojave#47]
今天更新下驱动顺便升级到10.14.4，一开始很顺利升级完进了系统

然后把kext修复了下权限后重启进入clover黑苹果入口却不见了，只剩下win系统的入口

求助，查不出什么原因orz

**Comment by yasuharaema** [comment]
系统配置同jardenliu一样

**Comment by yasuharaema** [comment]
补充下：升级前clover已更新到最新

**Comment by yasuharaema** [comment]
好像找到原因了。。作死不小心打开了apfs加密

现在不知道怎么解决。。

**Comment by yasuharaema** [comment]
利用时间机器恢复了，大家千万不要开那个加密啊。。

**Comment by jardenliu** [comment]
是那个文件加密？

**Comment by yasuharaema** [comment]
> 是那个文件加密？

是的，就是那个FileValut文件保险箱，之前没在注意升级后设置随手一开，没想到黑果不能开..

**Comment by jardenliu** [comment]
那个确实不能开了～
