### ISSUE TITLE
可以添加ubuntu支持吗

### ISSUE THREAD

**Issue by JosephDhF** [jardenliu/XPS15-9560-Mojave#50]
你好，是否可以添加Ubuntu启动支持哦，我的ubuntu是以前安装的，把原来的ubuntu相关cfg和efi文件夹放进来，还是启动不了。

**Comment by jizongFox** [comment]
EFI for both Mac and Ubuntu:
<img width="300" alt="WX20190416-085415@2x" src="https://user-images.githubusercontent.com/24821325/56211119-3a51b300-6025-11e9-94b9-9aca5ff43dc3.png">

**Comment by JosephDhF** [comment]
您好，上面图片的文件可以发一份么，我的Ubuntu卡在苹果图标没有任何反应，感谢。
email：joseph.hhfang@foxmail.com

**Comment by jizongFox** [comment]
@JosephDhF Ubuntu EFI is different from machine to machine. Just make sure that the EFI structure is similar. I sent you the folder anyway. Hope that helps.

**Comment by jardenliu** [comment]
Linux默认支持的

**Comment by JosephDhF** [comment]
我是启动3个系统，后来Ubuntu重装了一下，clover就可以引导了
