### ISSUE TITLE
安装卡在Waiting on <dict ID="8"><key>IOProviderClass<...

### ISSUE THREAD

**Issue by WatsonHS** [jardenliu/XPS15-9560-Mojave#51]
CPU：Intel I7 7700HQ
内存：16G(8G*2) 2400MHz DDR4
硬盘：三星 970 EVO 500G
BIOS版本：1.12.1
安装程序都没法进去，卡在了这里，然后就花屏了
![IMG_4109](https://user-images.githubusercontent.com/20162480/56598140-82289980-6626-11e9-8a0f-4515c3142402.JPG)
第一次装黑苹果..不知道是不是少了什么操作
望指点

**Comment by jardenliu** [comment]
1080还是4K的？

**Comment by WatsonHS** [comment]
> 1080还是4K的？

1080的

**Comment by jackhanyuan** [comment]
我从10.14.3升级10.14.4遇到了同样问题，安装时卡在“Waiting on <dict ID="0"><key>IOProviderClass</Key><string ID="1">IOResources</sting><key>IOResourceMatch</key>sting ID="2">boot”，随后出现禁行标志，这应该是USB问题，不过我的硬盘是海力士的，检查后发现是海力士硬盘未被识别，爬大量贴后找到了解决方法。
Comment: IONVMeFamily Preferred Block Size 0x10 -> 0x01 (c) Pike R. Alpha implemented by syscl adapted for 10.14.4 by Ricky
Name:    IONVMeFamily
find:    <F6C1100F 85440100 00>
replace: <F6C1010F 85440100 00>
