### ISSUE TITLE
海力士硬盘识别问题

### ISSUE THREAD

**Issue by guangcan** [jardenliu/XPS15-9560-Mojave#52]
您好，请问下你在论坛回复的海力士要打补丁是直接在config.plist里加代码还是要放文件进去？在论坛爬了几天的帖子也没解决这个问题

**Comment by jardenliu** [comment]
参见此帖: http://bbs.pcbeta.com/viewthread-1774117-1-1.html

**Comment by guangcan** [comment]
试过了，也是没用。。

**Comment by jardenliu** [comment]
那我也没什么太好的办法

**Comment by jardenliu** [comment]
毕竟我也没有海力士的硬盘可以做实验

**Comment by maxsos99** [comment]
最近也想说来弄XPS 15-9560的双系统，但硬盘容量实在太少才240G左右，如果想买1T的M.2 Pcie建议使用哪个呢?牌子来装呢? 谢谢

**Comment by jardenliu** [comment]
很多牌子都可以，我这台是东芝的

**Comment by maxsos99** [comment]
我买了一个Intel 660P 1T，使用此https://github.com/jardenliu/XPS15-9560-Mojave/tree/VirtualSmc，安装，可顺利到安装画面，但是在分割完硬盘后， 正式安装系统標示3分鐘的过程，不到幾秒，自动跳回DELL画面，我是直接安装10.14.4，请问有试过此版本了吗?

**Comment by jardenliu** [comment]
Comment: IONVMeFamily Preferred Block Size 0x10 -> 0x01 (c) Pike R. Alpha implemented by syscl adapted for 10.14.4 by Ricky
Name: IONVMeFamily
find: <F6C1100F 85440100 00>
replace: <F6C1010F 85440100 00>

**Comment by Elity** [comment]
10.14.5 能自动识别海力士SSD了
