### ISSUE TITLE
进系统前一瞬间重启

### ISSUE THREAD

**Issue by machdwj** [jardenliu/XPS15-9560-Mojave#58]
求助，用这个版本的clover 安装系统没问题。但是只能进一次系统。然后每次都是进度条跑完，进系统的一瞬间就黑屏重启了。试装了无数次了。我的是和你的配置一样。i7-7700  4k触摸屏  三星pm961硬盘  。。原配的大电池我改成小电池和一个1t的硬盘。。。

**Comment by jardenliu** [comment]
试试把pm961的硬盘先拆了，在1t硬盘上面安装
。看看会不会重启

**Comment by machdwj** [comment]
试过了。一样。今天发现不驱动显卡，显存31m，能进系统。同时用parallel 还可以运行两台虚拟机。。。奇怪

**Comment by jardenliu** [comment]
难道你的显卡还比较不一样？

**Comment by machdwj** [comment]
我看你的config是不是做了补丁？？我就是4k的屏呀

**Comment by jardenliu** [comment]
显卡不需要做什么补丁了吧

**Comment by Herrengit** [comment]
我跟你一样 后面我用-v解决了
