### ISSUE TITLE
好像蓝牙没驱动好

### ISSUE THREAD

**Issue by iPermanent** [jardenliu/XPS15-9560-Mojave#6]
我换的网卡DW1560的，蓝牙没有驱动成功，别的都OK

**Comment by jardenliu** [comment]
重建缓存，关机再开机

**Comment by iPermanent** [comment]
试过了  还是有些问题，另外，触摸板也驱不起来了，尴尬

**Comment by jardenliu** [comment]
触摸板没反应还是怎么的

**Comment by iPermanent** [comment]
嗯 完全没反应  我替换clover试试看

**Comment by iPermanent** [comment]
好了。我在https://github.com/MichaelVector/XPS15-9560-macOS10.14  这里找的clover替换进去 蓝牙也好了  触摸板也好了，不过他的clover不能用来做U盘启动，非常感谢，要两者结合才能好
