### ISSUE TITLE
I can't deactivate Bluetooth after last changes

### ISSUE THREAD

**Issue by LeLunZ** [jardenliu/XPS15-9560-Mojave#60]
It took like 1 minute to deactivate bluetooth and now it won't turn on again.

**Comment by jardenliu** [comment]
I know that war a bug, so don't turn off it. zzzz  fix it in a later version

**Comment by intel0753** [comment]
提供一个缓解措施，如果你的蓝牙还不能正常工作，你可以在BIOS中关闭WiFi和蓝牙，进入系统，然后再重启，进入BIOS打开WiFi和蓝牙，进入macOS后应该就能正常工作了，如果还不行，可以尝试在BIOS重新打开蓝牙和WiFi后，在Clover引导界面按下Fn+F11重置NVRAM来尝试解决问题。
-------------------------------------
Here's a way to mitigate this problem if the Bluetooth still doesn't work on your device. You can deactivate BOTH WiFi and Bluetooth in BIOS, then boot to an OS, and then restart the computer and enter the BIOS again to re-enable WiFi and BT, then boot into macOS, it should work again.
If it still can't work, you can try to press Fn+F11  during the Clover boot menu to reset NVRAM after re-enable WiFi and BT.

**Comment by shawnchan2014** [comment]
After doing what @intel0753 suggested, my WiFi and Bluetooth was still not working. What worse, I found that WiFi was not even working on Win10. However, after I ran the network diagnostic on Win10 and tried to turn off the network switch (with `fn + PrtScr` or `PrtScr`, the key right next to F12) and turned on again, it magically worked! If there's anyone encountering the same problem as I did, you could also try my solution:)
