### ISSUE TITLE
HWP and CPUFriendDataProvider.kext

### ISSUE THREAD

**Issue by nmnobre** [jardenliu/XPS15-9560-Mojave#61]
Hi! How did you build CPUFriendDataProvider.kext? Why did you set the EPP to 32?

**Comment by jardenliu** [comment]
The CPUFriend Git Repo README.md will tell you how ti build it.  Whats you mean the EPP. I cant understand what you said

**Comment by nmnobre** [comment]
Energy Performance Preference, it's one of the settings for HWP. So, if you followed such tutorial, on what MacBook Pro did you base the frequency vectors?
