### ISSUE TITLE
VirtualSMC的优点？以及触摸板kext的问题

### ISSUE THREAD

**Issue by ToCHONG** [jardenliu/XPS15-9560-Mojave#63]
1.其实fakesmc替换成virtualsmc的目的是什么？
2.在post-install文件夹中，PS2controller的文件与clover文件中的不一致，请问是要用哪个呢？
3.另外postintasll的是直接复制到others里还是用kext utility之类的安装？
谢谢

**Comment by jardenliu** [comment]
1. 你猜
2. 都一样的
3. 都放others

**Comment by ToCHONG** [comment]
。。。好吧。。。
