### ISSUE TITLE
关于键盘和usb网络共享

### ISSUE THREAD

**Issue by wjh422** [jardenliu/XPS15-9560-Mojave#65]
开机后存在一定几率键盘失效，外接usb键盘正常，触摸板正常，重启解决。
 #HoRNDIS.kext放入CLOVER/kexts/Other后没有效果（也可能是我自己的问题），下载安装HoRNDIS.pkg最新版本后第一次重启usb网络共享正常。关机后再次开机大概率出现自动重启问题（在白苹果进度条或者进入桌面约半分钟时或者链接安卓手机打开usb网络共享开关时）
谢谢！辛苦了 #

**Comment by jardenliu** [comment]
每次换了驱动，都重建缓存了吗

**Comment by wjh422** [comment]
horndis.kext依然是失效的

**Comment by jardenliu** [comment]
刚更新了HoRNDIS.kext，应该可以了

**Comment by jardenliu** [comment]
![image](https://user-images.githubusercontent.com/15191056/57983631-d3417700-7a86-11e9-9eac-ed8b3115e28c.png)

**Comment by wjh422** [comment]
多谢 辛苦！
另外键盘开机失灵重启一次才可以用的问题依然存在，
另外，再安装完瑞雨的usb网卡驱动之后，蓝牙可以搜索 但无法连接
