### ISSUE TITLE
Catalina dp2

### ISSUE THREAD

**Issue by buhlaze** [jardenliu/XPS15-9560-Mojave#70]
Can not get graphics to boot on catalina dp2.

**Comment by jardenliu** [comment]
not support yet.

**Comment by jardenliu** [comment]
https://github.com/jardenliu/XPS15-9560-Catalina-Preview/blob/master/README_EN.md

**Comment by jardenliu** [comment]
@buhlaze https://github.com/jardenliu/XPS15-9560-Catalina-Preview/blob/master/README_EN.md
