### ISSUE TITLE
请问4k版本会不会有唤醒闪屏或者花屏的情况

### ISSUE THREAD

**Issue by jiaonisi** [jardenliu/XPS15-9560-Mojave#72]
我之前用的XPS 9550 I7 4K的，本来好好的。后来突然有天开始只要一关屏幕（合盖、手动睡眠、自动睡眠）再唤醒，就各种闪屏，最开始就是闪一些细微的小白条，后来越来越厉害，简直能闪瞎眼，后来一查好像不少人有过这种问题，很难搞，属于非常顽固的疑难杂症。
所以想把9550给出了，换台9560 4K的，因为有这方面顾虑，所以想请教下9560 4K有没有这方面的问题，麻烦了。

**Comment by jardenliu** [comment]
目前没有出现你说的这种现象

**Comment by jiaonisi** [comment]
好的 多谢

**Comment by jardenliu** [comment]
@jiaonisi 有条件可以上9570或者OLED版本的7590

**Comment by Xuedingzheng** [comment]
9550需要改什么吗，还是可以直接用

**Comment by jardenliu** [comment]
9550不适用
