### ISSUE TITLE
电池百分比充电的时候不动

### ISSUE THREAD

**Issue by renchui** [jardenliu/XPS15-9560-Mojave#74]
只有充电的时候不会动，拔掉过后会更新，掉电也正常。

**Comment by robinwang1998** [comment]
我的问题可能严重一些 热插拔充电接口的时候会出现黑屏重启的情况 不知道是不是电源管理芯片出了问题

**Comment by jardenliu** [comment]
换成VirtualSMC之后一直有这个问题，等待VirtualSMC更新驱动把

**Comment by alex1993ho** [comment]
满电插充电器会黑屏重启，不满电情况下看运气

**Comment by jardenliu** [comment]
@renchui 试试把ACPI/patched 下面的SSDT-BATC.aml删了

**Comment by jardenliu** [comment]
@renchui 亲测有效

**Comment by renchui** [comment]
> @renchui 亲测有效

感谢~回去试试
