### ISSUE TITLE
10.14.6无法更新

### ISSUE THREAD

**Issue by zzzqqqhhh** [jardenliu/XPS15-9560-Mojave#75]
如题

**Comment by jardenliu** [comment]
请描述一下具体情况

**Comment by zzzqqqhhh** [comment]
clover  boot mac install from mac 启动到这一项时无法进入升级安装界面，继续重启

**Comment by jardenliu** [comment]
请确认升级过配置

**Comment by jardenliu** [comment]
不行的话，改用此配置试试https://github.com/jardenliu/XPS15-9560-Catalina-Preview

**Comment by zzzqqqhhh** [comment]
> 不行的话，改用此配置试试https://github.com/jardenliu/XPS15-9560-Catalina-Preview

使用这个配置能正常进系统，但还是无法更新，重启后反复重启。我的配置9560 i5 4k 8+256

**Comment by ToCHONG** [comment]
我升级过，确实clover boot mac install from mac 启动到这一项时无法进入升级安装界面，继续重启，但是重启多两三次就可以了

**Comment by robinwang1998** [comment]
使用提供的上一版配置更新到10.14.6会掉触摸板驱动 不知道能不能解决
9560 i5 8g 用户

**Comment by robinwang1998** [comment]
但是可以连接鼠标 打开系统偏好设置提醒搜索蓝牙触摸板

**Comment by jardenliu** [comment]
@zzzqqqhhh 绝大多数，人都可以无痛升级14.6，请检查配置是否一直，bios设置是否正确

**Comment by jardenliu** [comment]
@robinwang1998 无论升级还是全新安装，完成后第一件事都是重建缓存

**Comment by zzzqqqhhh** [comment]
> @zzzqqqhhh 绝大多数，人都可以无痛升级14.6，请检查配置是否一直，bios设置是否正确
**
bios设置没问题啊，就是一直重启重启，重启过10次也没效果。

**Comment by jardenliu** [comment]
@zzzqqqhhh 加入`keepSyms =1` 和 `debug=0x100` 两个启动参数，阻止重启，然后把报错的截图发上来
