### ISSUE TITLE
建群意见征集

### ISSUE THREAD

**Issue by jardenliu** [jardenliu/XPS15-9560-Mojave#77]
觉得有必要建个群交流的，麻烦再下方留个言。顺便备注下要建微信还是QQ

**Comment by robinwang1998** [comment]
有必要 刚开始玩黑苹果太需要这种经验分享了

**Comment by intel0753** [comment]
赞同，能买同一款/系列电脑的话，可聊度还是很高的，证明大家的需求还是很相似的。

**Comment by parchrome** [comment]
很有必要

**Comment by Gaomojiang** [comment]
建群好，方便大家交流沟通。比方说我是I5版本，自行升级的4K屏幕

**Comment by Gaomojiang** [comment]
大佬，你现在用的bios什么版本

**Comment by xianzhixianzhixian** [comment]
建一个QQ群吧，我在QQ里找不到你了。。。原来你还QQ教我装的。。。

**Comment by alex1993ho** [comment]
QQ群分享文件比较方便吧

**Comment by ToCHONG** [comment]
有必要，大家有什么问题一起解决比较方便

**Comment by WenJunDuan** [comment]
TG吧，百无禁忌，方便

**Comment by jardenliu** [comment]
@robinwang1998 @intel0753 @parchrome @Gaomojiang @WenJunDuan @Gaomojiang @xianzhixianzhixian @alex1993ho @ToCHONG Q群：161385229
