### ISSUE TITLE
Mac 10.14   关于耳机问题

### ISSUE THREAD

**Issue by BillTaozi** [jardenliu/XPS15-9560-Mojave#8]
重新安装了全新的10.14 系统后，耳机按照教程不起作用
![2018-09-28 20 33 42](https://user-images.githubusercontent.com/35515198/46208718-2e8af180-c35e-11e8-8b07-75d21bc01ceb.png)如图所示，怎么解决呢

**Comment by jardenliu** [comment]
以前用的combo jack?

**Comment by BillTaozi** [comment]
是的，不过我是制作了全新的安装U盘后进行全新安装的系统，在双击文件时出现的这个错误，不过好在解决了，就是用终端重建了缓存！
