### ISSUE TITLE
自动重启问题

### ISSUE THREAD

**Issue by houbo0601** [jardenliu/XPS15-9560-Mojave#9]
处理器i5这一款，固态硬盘是三星PM961，其他配置一样，正常安装使用，但是隔几分钟就会自动重启

**Comment by jardenliu** [comment]
PM981吧？

**Comment by houbo0601** [comment]
是961

**Comment by jardenliu** [comment]
http://bbs.pcbeta.com/viewthread-1774117-1-1.html 你可以看看这个帖子

**Comment by jardenliu** [comment]
Comment: IONVMeFamily Preferred Block Size 0x10 -> 0x01 (c) Pike R. Alpha implemented by syscl adapted for 10.13.x-10.14 by Ricky
Name:    IONVMeFamily
find:    <f6c1100f 85410100 00>
replace: <f6c1010f 85410100 00>

**Comment by jardenliu** [comment]
Comment: IONVMeFamily Preferred Block Size 0x10 -> 0x02 (c) Pike R. Alpha implemented by syscl adapted for 10.13.x-10.14 by Ricky
Name:    IONVMeFamily
find:    <f6c1100f 85410100 00>
replace: <f6c1020f 85410100 00>

**Comment by jardenliu** [comment]
Comment: IONVMeFamily Preferred Block Size 0x10 -> 0x08 (c) Pike R. Alpha implemented by syscl adapted for 10.13.x-10.14 by Ricky
Name:    IONVMeFamily
find:    <f6c1100f 85410100 00>
replace: <f6c1080f 85410100 00>

**Comment by jardenliu** [comment]
第一组无效的话  尝试下面三组

**Comment by houbo0601** [comment]
重新换了一个clover，重新检查了bios配置好了，原因没有细究

**Comment by yxrdydh** [comment]
我觉得可能是VoodooI2C驱动的锅，我更新VoodooI2C到最新自己编译版本后，没再出现过重启问题。
